apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfe-front-deployment
  labels:
    app: pfe-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfe-front
  template:
    metadata:
      labels:
        app: pfe-front
    spec:
      containers:
      - name: pfe-front
        image: default-route-openshift-image-registry.apps-crc.testing/pfe/pfe-front:latest
        ports:
        - containerPort: 8080 # Replace with the actual port used by your container
        env:
        - name: ENV_VAR_NAME  # Add environment variables as needed
          value: "value"  # Set appropriate values for your environment variables
        imagePullPolicy: Always
